### ISSUE TITLE
[FR-1] <Past Organization History >

### ISSUE THREAD

**Issue by locphan0321** [WSU-4110/Volunteer-Opportunities#1]
### Goal

Volunteers should be able to see past organizations that they have interacted with on their profile page

### Description

It’s important for users to be able to see what kinds of interactions they have had with organizations in the past for mental bookkeeping. These interactions will therefore be kept available on their profile page for them to track the date and type of interaction that they had with those organizations. 

### Stakeholders

Volunteers

### Date

11/26/24

### Version

3.0

### Origin

This requirement came up while we were working on our presentation.

### Priority of the proposed feature

Could have

**Comment by SebastianNewberry** [comment]
This is complete
