### ISSUE TITLE
[FR-13] <Toggle View>

### ISSUE THREAD

**Issue by julbri26** [WSU-4110/Volunteer-Opportunities#10]
### Goal

The system will allow users to toggle between viewing the website as an organization or as a volunteer through a button on the navigation bar.

### Description

There will be a toggle on the navigation bar, and it will enable users to switch view mode, as a volunteer or as an organization. The content and features on the website will be adjusted based on the selected view. 

### Stakeholders

Volunteers, Organizations

### Date

10/1/2024

### Version

1.0

### Origin

We came up with this idea in our first meeting. We want to ensure that users can easily switch their role without needing to log out or create a separate account.

### Priority of the proposed feature

Must have

**Comment by parsahl0707** [comment]
LGTM
