### ISSUE TITLE
[FR-7] <Editing account profile information>

### ISSUE THREAD

**Issue by locphan0321** [WSU-4110/Volunteer-Opportunities#11]
### Goal

Users need to be able to edit existing accounts they have made for volunteers and organizations.

### Description

Users must update and change their profile information after their account is created.  Changing information like pictures, descriptions or their names is important as this information can change over time.  

### Stakeholders

Volunteers, Organizations

### Date

10/29/24

### Version

2.0

### Origin

This idea is from the first meeting. We wanted the profiles to be editable giving the user the ability to change what information was shown on their profiles.

### Priority of the proposed feature

Should have

**Comment by parsahl0707** [comment]
LGTM
