### ISSUE TITLE
[FR-11] <Page Navigation>

### ISSUE THREAD

**Issue by julbri26** [WSU-4110/Volunteer-Opportunities#14]
### Goal

The user will be able to navigate between website pages (home, explore, messaging, and profile).

### Description

Due to the multiple functions of our website, our website will have multiple pages. As a result, a navigation tool of some sort is required to allow the user to move from one page to another. This will allow the user to easily view any desired information. 

### Stakeholders

Volunteers, Organizations

### Date

10/1/2024

### Version

1.0

### Origin

This requirement was formed in our first meeting as it is necessary to be able to navigate between pages.

### Priority of the proposed feature

Must have

**Comment by parsahl0707** [comment]
LGTM
