### ISSUE TITLE
[FR-10] <Search for keywords>

### ISSUE THREAD

**Issue by julbri26** [WSU-4110/Volunteer-Opportunities#15]
### Goal

The user will be able to search for specific organizations or volunteers that relate to the keywords they type in.

### Description

Organizations may want people with specific skills to work with them and volunteers may want to work for specific organizations. A solution to this would be a search bar that allows users to search for keywords to find what they are looking for. 

### Stakeholders

Volunteers, Organizations

### Date

10/29/24

### Version

2.0

### Origin

We thought of this when we first discussed the format of our website. We knew that we wanted a search function.

### Priority of the proposed feature

Should have

**Comment by parsahl0707** [comment]
Task #48 and #49 implemented this.

**Comment by parsahl0707** [comment]
LGTM
