### ISSUE TITLE
[FR-9] <Contact Access Through Listings>

### ISSUE THREAD

**Issue by locphan0321** [WSU-4110/Volunteer-Opportunities#16]
### Goal

The system will allow users to contact volunteers and organizations through listings.

### Description

Volunteers and Organizations will be able to access a communication feature. Volunteers will be able to contact organizations about opportunities, and organizations will be able to reach out to volunteers who have expressed interest in their listings.  

### Stakeholders

Volunteers, Organizations

### Date

11/26/24

### Version

3.0

### Origin

We came up with this idea in our first meeting. We wanted to ensure that users receive messages quickly and can communicate directly with each other on the website.

### Priority of the proposed feature

Must have

**Comment by parsahl0707** [comment]
Sebastian worked on this

**Comment by parsahl0707** [comment]
LGTM
