### ISSUE TITLE
[FR-2] <Creating Organizations>

### ISSUE THREAD

**Issue by locphan0321** [WSU-4110/Volunteer-Opportunities#2]
### Goal

Volunteers should be able to create organizations

### Description

The app is planned to have users create organizations and organizations create listings.  Allowing users to create organizations attaches the listings to something other than a personal profile. Creating multiple organizations can allow users to group listings in different ways. 

### Stakeholders

Organizations

### Date

10/1/24

### Version

1.0

### Origin

This requirement came up while working on our first presentation

### Priority of the proposed feature

Must have

**Comment by IanCro12** [comment]
Set up add organization page to allow users to add create multiple organizations

**Comment by parsahl0707** [comment]
LGTM
