### ISSUE TITLE
[NFR-6] <Easy Page Navigation>

### ISSUE THREAD

**Issue by julbri26** [WSU-4110/Volunteer-Opportunities#20]
### Goal

Users will be able to access any page within 5 clicks.

### Description

Users should be able to go to a new page or go back to a previous page without confusion. As a result, the user can access any page on our website within 5 clicks. This will prevent the user from getting “lost”. 

### Stakeholders

Volunteer, Organization

### Date

11/26/2024

### Version

3.0

### Origin

We discussed this during our first meeting and thought this would cover the “useability” category of non-functional requirements.

### Priority of the proposed feature

Could have

**Comment by julbri26** [comment]
Accidental duplicate

**Comment by parsahl0707** [comment]
LGTM
