### ISSUE TITLE
[FR-3] <Creating listings>

### ISSUE THREAD

**Issue by locphan0321** [WSU-4110/Volunteer-Opportunities#3]
### Goal

Organizations need to be able to create listings including a list of desired skills

### Description

Listings are how organizations reach out to volunteers.  Organizations should be able to show what skills they are looking for by including the skills they desire in a listing. 

### Stakeholders

Organizations

### Date

10/1/24

### Version

1.0

### Origin

This requirement came up while working on our first presentation.

### Priority of the proposed feature

Must have

**Comment by parsahl0707** [comment]
LGTM
