### ISSUE TITLE
[BUG] <Talents not display aesthetically on messaging page>

### ISSUE THREAD

**Issue by parsahl0707** [WSU-4110/Volunteer-Opportunities#33]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

The messaging page displays the talents of each volunteer in plain-text.

### Expected Behavior

The talents should be displayed aesthetically.

### Steps To Reproduce

1. Go to the messaging page
2. Find a volunteer with talents

### Environment

```markdown
- OS: macOS Sonoma 14.6.1
- Node: v22.7.0
- npm: 10.8.2
- Safari: Version 17.6 (19618.3.11.11.5)
```

### Anything else?

The explore page and messaging page should leverage the same "Talent" React component to modularize and simplify code.

_No response_

**Comment by SebastianNewberry** [comment]
This has been fixed.
