### ISSUE TITLE
[TASK] Create Initial Home Page

### ISSUE THREAD

**Issue by julbri26** [WSU-4110/Volunteer-Opportunities#43]
### Title

Create Initial Home Page

### Description

Have a home page created on the site for the user to see. This page should have some information about the site and it's creators.

### Acceptance criteria

Have a functional home page.

### Estimate

8

### Associated feature

#5 [FR-16] Homepage Display

**Comment by julbri26** [comment]
Finished in sprint 1

**Comment by parsahl0707** [comment]
LGTM
