### ISSUE TITLE
[TASK] Configure OAuth with Google

### ISSUE THREAD

**Issue by SebastianNewberry** [WSU-4110/Volunteer-Opportunities#44]
### Title

Configure OAuth with Google by utilizing Google Api Console.

### Description

Log into the [Google Auth Console](https://console.cloud.google.com/) with your Google credentials. Then create an authorized JavaScript origin for Google to recognize what site you are coming from, and an authorized redirect url to authorize Google to redirect users to a certain url. Then configure next-auth within the database

### Acceptance criteria

- The database has Next-Auth setup with accounts, users, verificationTokens, and Sessions tables configured properly (See [Next-Auth Docs](https://next-auth.js.org/getting-started/introduction) for more info. 
- The Google Api Console has redirect and JavaScript origin urls configured properly.

### Estimate

4

### Associated feature

#6

**Comment by parsahl0707** [comment]
LGTM
