### ISSUE TITLE
[TASK] Configure messages to send between multiple users

### ISSUE THREAD

**Issue by SebastianNewberry** [WSU-4110/Volunteer-Opportunities#46]
### Title

Set up database relations with conversations to keep track of conversations between users and organizations.

### Description

- Create a database schema that supports conversations between organizations and volunteers. Keep track of sender and receiver Ids for a message.
- Show messages on the frontend. Search for all conversations that the user has participated in, and if the user switches from volunteer view to organization view, then show different conversations that belong to the organization instead.
- Inside of the message box, the user should be able to see who sent a message and should be able to differentiate between the sender and receiver of a message.

### Acceptance criteria

- The database should have the correct design describe above. Inside of the database, there should be columns storing time the message was sent, and relationships between the message and the specific conversation should also be setup, and there should be content for every message.
- The frontend should be very responsive and should show conversations very quickly when switching between organization and volunteer views. The frontend should also show everything described above. Eventually, pusher will be setup in sprint 3 to add realtime messaging so users can see messages from other users in realtime without having to refresh the page.

### Estimate

10

### Associated feature

#8

**Comment by parsahl0707** [comment]
LGTM
