### ISSUE TITLE
[TASK] Set up aws s3

### ISSUE THREAD

**Issue by IanCro12** [WSU-4110/Volunteer-Opportunities#47]
### Title

Add put and get for images to a S3 bucket

### Description

Set up AWS S3 bucket for image storage to allow images to be added and accessed in the bucket

### Acceptance criteria

Put and Get methods for S3 bucket

Store file key in database so they can be accessed latter

### Estimate

8

### Associated feature

FR-7

**Comment by parsahl0707** [comment]
LGTM
