### ISSUE TITLE
[FR-16] <Homepage Display>

### ISSUE THREAD

**Issue by julbri26** [WSU-4110/Volunteer-Opportunities#5]
### Goal

The homepage will display “About Us” information that clarifies our mission and background to users coming to our website.

### Description

When the user first visits our website, we want them to be greeted with a page that will explain what our website is about. This will let the user know what they will see when navigating our site. 

### Stakeholders

Volunteer, Organization

### Date

10/29/24

### Version

2.0

### Origin

When we first discussed what we wanted our website to look like we knew we wanted a home page of some sort.

### Priority of the proposed feature

Should have

**Comment by parsahl0707** [comment]
LGTM
