### ISSUE TITLE
[TASK] Change s3 to use static urls

### ISSUE THREAD

**Issue by IanCro12** [WSU-4110/Volunteer-Opportunities#55]
### Title

Change s3 to static urls

### Description

Change s3 to allow the website to use static URLs to access images instead of presigned URLS

### Acceptance criteria

Images are now stored in a way that allows for public read access

### Estimate

4

### Associated feature

[FR-7] though this change will make it easier for all pages to use stored images.

**Comment by parsahl0707** [comment]
LGTM
