### ISSUE TITLE
[FR-15] <Viewing history of a conversation>

### ISSUE THREAD

**Issue by julbri26** [WSU-4110/Volunteer-Opportunities#6]
### Goal

Users and organizations will be able to view at least their last 50 messages sent to and from a specific profile when the page loads for a specific conversation.

### Description

When a user decides to message another user on our platform that it has had a conversation with before, the user will see at least the previous 50 messages that have been sent to and received from that other user. This means our system can hold at least 50 messages for every conversation that starts between two users on our platform. These two users could be volunteers or organizations. It doesn’t matter who they are as long as they initiate a conversation. 

### Stakeholders

Volunteer, Organization, Database Server

### Date

11/26/2024

### Version

3.0

### Origin

We came up with this idea when we were brainstorming ideas of using a messaging system in our platform. This came up in our first meeting after presentation 1.

### Priority of the proposed feature

Could have

**Comment by SebastianNewberry** [comment]
This has been completed.
