### ISSUE TITLE
[BUG] <Image upload not working on organization page>

### ISSUE THREAD

**Issue by parsahl0707** [WSU-4110/Volunteer-Opportunities#66]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

After uploading an image to the profile picture of the organization page, I don't see the image even after pressing submit.

### Expected Behavior

The image should display on the profile picture after pressing submit.

### Steps To Reproduce

1. Go to an organization
2. Edit the profile picture
3. Submit

### Environment

```markdown
- OS: macOS Sequoia 15.1.1
- Node: v23.3.0
- npm: 10.9.0
- Safari: Version 18.1.1 (20619.2.8.11.12)
```

**Comment by IanCro12** [comment]
https://github.com/WSU-4110/Volunteer-Opportunities/commit/14072fac283e445ca982bea5bf71f83cbca4325e 

In organizations.tsx passed the wrong value 172 to actions.tsx
