### ISSUE TITLE
[BUG] <Profile Pictures on Homepage fail to display>

### ISSUE THREAD

**Issue by parsahl0707** [WSU-4110/Volunteer-Opportunities#67]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Occasionally when you go to the homepage, the profile pictures don't display. The following error shows up in the console: [Error] Failed to load resource: the server responded with a status of 404 (Not Found) (Ian-Profile.png, line 0). The images display properly when you reload the page again.

### Expected Behavior

The profile pictures should display without error.

### Steps To Reproduce

1. Open homepage
2. If error doesn't pop up go to another page and spend some time there
3. Come back to homepage
4. Repeat if error hasn't happened yet

### Environment

```markdown
- OS: macOS Sequoia 15.1.1
- Node: v23.3.0
- npm: 10.9.0
- Safari: Version 18.1.1 (20619.2.8.11.12)
```

**Comment by SebastianNewberry** [comment]
This has been fixed.
