### ISSUE TITLE
[FR-5] <Storage of Essential Profile Information>

### ISSUE THREAD

**Issue by locphan0321** [WSU-4110/Volunteer-Opportunities#7]
### Goal

When the user opens their profile page, they should be able to see their profile information even if they close the website tab after creating a profile

### Description

Our system will be able to store profile information of volunteers and organizations. The profile information will not be lost or corrupted for the entirety of the time our website is functional. This system will be able to store thousands of different profiles. Whenever a user wants to pull up their information, they should be able to see it within a couple seconds. 

### Stakeholders

Volunteer, Organization, Database Server

### Date

10/1/24

### Version

1.0

### Origin

We came up with this idea during the initial planning phase of our design before presentation 1.

### Priority of the proposed feature

Must have

**Comment by IanCro12** [comment]
Got a working profile page to add volunteer data

**Comment by IanCro12** [comment]
Add edit profile to add volunteer information

**Comment by IanCro12** [comment]
Closing

**Comment by parsahl0707** [comment]
LGTM
