### ISSUE TITLE
[FR-14] <Initiate Individual Conversations>

### ISSUE THREAD

**Issue by julbri26** [WSU-4110/Volunteer-Opportunities#8]
### Goal

All users will be able to initiate individual conversations with other users in their messages by clicking on a desired profile image and pressing a button to send a message

### Description

Users who are either volunteers or organizations can start conversations by clicking on the profile image of another user and pressing a button to send message. This will redirect them to the messaging page for direct communication. This feature aims to improve engagement by allowing easy interaction within the website without needing to switch to an external communication tool. 

### Stakeholders

Volunteers, Organizations

### Date

11/26/2024

### Version

3.0

### Origin

We came up with this idea in our first meeting. We want to ensure that users can easily engage in one-on-one conversations directly from profiles they are interested in.

### Priority of the proposed feature

Should have

**Comment by SebastianNewberry** [comment]
This has been finished. Messaging is mostly done and users can initiate conversations with each other.

**Comment by parsahl0707** [comment]
LGTM
