### ISSUE TITLE
[FR-6] <Account Creation with Third-Party Login and Additional User Information>

### ISSUE THREAD

**Issue by locphan0321** [WSU-4110/Volunteer-Opportunities#9]
### Goal

The system will allow users to log in using services like Google, Facebook, Discord, or GitHub, and they should be able to add or edit their name, email, and profile picture.

### Description

Users can create their account and log in using their Google, Facebook, Discord, or GitHub account. The system will allow them to provide or modify their basic credentials including name, email, and profile picture. 

### Stakeholders

Volunteers, Organizations

### Date

10/1/24

### Version

1.0

### Origin

We came up with this idea in our first meeting. We wanted to ensure that users could log in easily and customize their profile information for better personalization.

### Priority of the proposed feature

Must have

**Comment by parsahl0707** [comment]
LGTM
